name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2]
        illuminate: [^10.0, ^11.0, ^12.0]


    name: PHP ${{ matrix.php }} & Illuminate ${{ matrix.illuminate }}

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - run: composer update --no-interaction
      - run: vendor/bin/pest